### ISSUE TITLE
Update lib 

### ISSUE THREAD

**Issue by sunil-singh-chaudhary** [luckycreationsindia/msg91#1]
hi i want to implement msg91 in flutter but what i am seeing is in flutter the dependency isnt updated from last 1 year did it move somewhere else or it in process pls reply

**Comment by luckycreationsindia** [comment]
Hey,

I was not actively using this library. I'll update the libs and push the update soon.

**Comment by luckycreationsindia** [comment]
I published latest release with updated dependencies. Let me know if you need any changes. I'm closing this issue.

**Comment by sunilsinghchaudhary00** [comment]
Thanks for the quick reply it will really hepful to use the lastest version if you can update Readme and sample examaple i only want to know is


3 | Resend OTP | 🟡
-- | -- | --
4 | Verify OTP

is now working or not

**Comment by luckycreationsindia** [comment]
I've updated new version 1.0.3+1

which includes API Wrapper for msg91 official APIs. I won't be able to check as I don't have verified header in msg91. If possible can you verify if it's working?

**Comment by luckycreationsindia** [comment]
You can check example in here:

https://pub.dev/packages/msg91/example

Quick reference:

```dart
import 'package:msg91/msg91.dart';
import 'package:msg91/src/msg91_otp.dart';

void main() {
final msg91 = Msg91().initialize(authKey: "AUTH_KEY");
final otp = msg91.getOtp();

otp.send(mobileNumber: mobile, options: OtpOptions(templateId: templateId)).then((value) {
    print("Response: $value");
  }).catchError((err) {
    print("Err Response: $err");
  });

otp.verify(otp: "123456", mobileNumber: mobile).then((value) {
    print("Response: $value");
  }).catchError((err) {
    print("Err Response: $err");
  });
  
  otp.resend(mobileNumber: mobile, type: ResendOTPType.VOICE).then((value) {
    print("Response: $value");
  }).catchError((err) {
    print("Err Response: $err");
  });
}
```
